// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Commands.Main.PingAsync(DisCatSharp.CommandsNext.CommandContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Commands.Main.SayAsync(DisCatSharp.CommandsNext.CommandContext,System.String)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Commands.Main.ShutdownAsync(DisCatSharp.CommandsNext.CommandContext)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.Client_Heartbeated(DisCatSharp.DiscordClient,DisCatSharp.EventArgs.HeartbeatEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.Client_Ready(DisCatSharp.DiscordClient,DisCatSharp.EventArgs.ReadyEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.Client_Resumed(DisCatSharp.DiscordClient,DisCatSharp.EventArgs.ReadyEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.Client_SocketClosed(DisCatSharp.DiscordClient,DisCatSharp.EventArgs.SocketCloseEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.Client_SocketErrored(DisCatSharp.DiscordClient,DisCatSharp.EventArgs.SocketErrorEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.Client_SocketOpened(DisCatSharp.DiscordClient,DisCatSharp.EventArgs.SocketEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.CNext_CommandErrored(DisCatSharp.CommandsNext.CommandsNextExtension,DisCatSharp.CommandsNext.CommandErrorEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.Discord_ApplicationCommandCreated(DisCatSharp.DiscordClient,DisCatSharp.EventArgs.ApplicationCommandEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.Discord_ApplicationCommandDeleted(DisCatSharp.DiscordClient,DisCatSharp.EventArgs.ApplicationCommandEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("DocumentationHeader", "MethodDocumentationHeader:The method must have a documentation header.", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.Discord_ApplicationCommandUpdated(DisCatSharp.DiscordClient,DisCatSharp.EventArgs.ApplicationCommandEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.Discord_ApplicationCommandCreated(DisCatSharp.DiscordClient,DisCatSharp.EventArgs.ApplicationCommandEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.Discord_ApplicationCommandDeleted(DisCatSharp.DiscordClient,DisCatSharp.EventArgs.ApplicationCommandEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.Discord_ApplicationCommandUpdated(DisCatSharp.DiscordClient,DisCatSharp.EventArgs.ApplicationCommandEventArgs)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.RegisterCommands(DisCatSharp.CommandsNext.CommandsNextExtension,DisCatSharp.ApplicationCommands.ApplicationCommandsExtension)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:DisCatSharp.Examples.Basics.Main.Bot.RegisterEventListener(DisCatSharp.DiscordClient,DisCatSharp.ApplicationCommands.ApplicationCommandsExtension,DisCatSharp.CommandsNext.CommandsNextExtension)")]
